### ISSUE TITLE
Docker - Error when Running Resque workers

### ISSUE THREAD

**Issue by CreativeBulma** [terramar-labs/packages#118]
Hi,

using docker-compose configuration I get an error when running the Resque Workers:

[Resque_RedisException]
  Error communicating with Redis: Connection to Redis redis-master:6379 failed after 1 failures.Last Error : (1) php_network_getaddresses: getaddrinfo failed: Name or service not known

To be more precise.
When running the following command
```shell
docker exec -t packages_web_1 /bin/bash -c \
>     'cd /app && bin/console resque:worker:start'
```
everything seems ok
```shell
Executing nohup /usr/local/bin/php  /app/src/../bin/resque > /app/src/../logs/resque.log 2>&1 & echo $!...
Starting 1 worker on 812897cc30d8 for * queues
```

But when I try the hook
```shell
curl -X POST http://MY_SERVER/webhook/56/receive
```
Then I got a 500 error with the message: [Resque_RedisException]
  Error communicating with Redis: Connection to Redis redis-master:6379 failed after 1 failures.Last Error : (1) php_network_getaddresses: getaddrinfo failed: Name or service not known

How to fix it ?
I know how to fix it when running on my server directly but when using docker.

**Comment by CreativeBulma** [comment]
Fixed.
If anyone facing the same issue, find below my working docker-compose.yml file:

```yaml
version: '2'
services:
  web:
    image: webdevops/php-nginx:7.1
    volumes:
      - .:/app
      - ./docker/nginx/vhost.common.d/vhost.common.conf:/opt/docker/etc/nginx/vhost.common.d/10-location-root.conf
    links:
      - redis-master
    environment:
      - WEB_DOCUMENT_ROOT=/app/web
    expose:
      - "80"
  redis-master:
    image: redis:3.2
    container_name: redis-master
    expose:
      - "6379"
```
