### ISSUE TITLE
after install "no database selected" error

### ISSUE THREAD

**Issue by szabogyula** [terramar-labs/packages#12]
After successful install and configuration I got these error in web interface and `bin/console orm:schema-tool:create`

`"SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected"`

The database is created and the authentication working and I think the config.yml is correct:

```
security:
  # Username and password to access the web management interface
  username: admin
  password: xxxx

doctrine:
  mapping:
    default:
      paths: [ '%app.root_dir%/src/Entity', '%app.root_dir%/src/Plugin' ]
      namespace: Terramar

  database:
    # Any Doctrine driver
    driver: pdo_mysql
    host: 127.0.0.1
    database: packages
    user: packages
    password: xxxxxx

   
resque:
  host:     'unix:/var/run/redis/redis.sock'
  port:     ~
  database: 0

```
