### ISSUE TITLE
bin/console orm:schema-tool:create throws error

### ISSUE THREAD

**Issue by joostvanveen** [terramar-labs/packages#24]
I'm not sure whether this is a bug or that I'm doing something wrong. 

I installed packages as per http://docs.terramarlabs.com/packages/3.1/getting-started/installation. All goes well, until I run `bin/console orm:schema-tool:create`. That command throws a MySQL error (or rather, three times the same one):

```
[Doctrine\DBAL\Exception\ConnectionException]
  An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)
```

I cannot for the life of me figure out why Doctrine tries to connect using 'root'@'localhost'  with no password, as I have another with WITH password specified in `config.yml`. `config.yml` is in the project root, same location as `config.yml.dist`

Here are the contents of my `config.yml` file:

```
security:
  # Username and password to access the web management interface
  username: ******
  password: ******

doctrine:
  mapping:
    default:
      paths: [ '%app.root_dir%/src/Entity', '%app.root_dir%/src/Plugin' ]
      namespace: Terramar

  database:
    # Any Doctrine driver
    driver: pdo_mysql

    # Options
    ## path: %app.root_dir%/database.sqlite
    host: 127.0.0.1
    user: packages
    password: ******
    dbname: packages

resque:
  host:     'unix:/tmp/redis.sock'
  port:     ~
  database: 0
```
