### ISSUE TITLE
feature: access to the repository only to members

### ISSUE THREAD

**Issue by strausmann** [terramar-labs/packages#73]
Hello,

Is there a way to allow only deposited users access to the repository via username and password or a token? If possible, these users / tokens should be managed by means of an API request.

Thanks 

Regards
Bjoern

**Comment by tyler-sommer** [comment]
This feature was actually added in 3.2.

Specify `secure_satis: true` in your config.yml and users will be required to login with the username and password (also configured in config.yml) to see or download any packages.

Excerpt example from config.yml:

```yaml
#... other config items

packages:
  # If set, username and password will be required when attempting to access
  # Satis-generated files.
  secure_satis:  false # Change this to true
```

I'm closing this issue. Please open a new one if you have any other problems.

Thanks again for using Packages!
